### ISSUE TITLE
Issue with LLM response 'invalid json'

### ISSUE THREAD

**Issue by void-sys1** [wAIfu-DEV/w-AI-fu#5] opened 2023-06-02 08:21 UTC
it keeps saying 'Could not reach the w-AI-fu application, it may have been closed.' whilst the program was still open, and the program says 'received incorrect json from llm' it also mentioned a system overload or an error

**Comment by wAIfu-DEV** [comment] 2023-06-02 09:00
'received incorrect json from llm' means there was an error with the Python script responsible for communicating with the NovelAI API.

This can be caused by multiple things:
- wrong credentials
- no internet
- some other unknown bug

But it might also be caused by the system error you mentioned, I'd be grateful if you could copy-paste the description of the error here.

**Comment by void-sys1** [comment] 2023-06-02 09:09
will a screenshot work?

**Comment by wAIfu-DEV** [comment] 2023-06-02 09:11
sure

**Comment by void-sys1** [comment] 2023-06-02 09:15
![2023-06-02 (2)](https://github.com/wAIfu-DEV/w-AI-fu/assets/121269623/5817b0df-6293-4d20-b4c8-a58f67bf22ac)
here!

**Comment by wAIfu-DEV** [comment] 2023-06-02 09:20
Thank you, I'll investigate when I get back home

**Comment by void-sys1** [comment] 2023-06-02 09:45
okay, thank you!!

**Comment by void-sys1** [comment] 2023-06-02 10:36
soo- turns out i had entered the wrong mail lol sry!!
i fixed it tho

**Comment by void-sys1** [comment] 2023-06-02 10:42
oops, it seems that it times out after the first message

**Comment by wAIfu-DEV** [comment] 2023-06-02 11:08
What do you mean by timeout, do you have a new error?

**Comment by void-sys1** [comment] 2023-06-02 11:27
yes, hold on, i just closed the program

**Comment by xxandeer** [comment] 2023-06-02 11:43
Isn't it better to close this case because the error didn't exist and instead open a new case for the new problem? In this way, it will be easier for other users to find a possible fix if they have the same problem.

**Comment by void-sys1** [comment] 2023-06-02 12:42
good idea!!

**Comment by void-sys1** [comment] 2023-06-02 12:43
it seems to have fixed itself, somehow

**Comment by wAIfu-DEV** [comment] 2023-06-02 19:22
A bug that fixes itself is somehow worse than one that doesn't...

Anyway, I'll close this issue for the response of the LLM, if you get another issue please open a new thread.

- What was the issue:
    Error 'received invalid json from LLM' after sending input.

- What was the cause:
    Invalid credentials.

- How to prevent it in the future:
    Have better, more insightful error messages for errors coming from python scripts.
    Find a way to verify credentials before error.

**Closed** 2023-06-02 19:23 UTC
